const SITE = {
  brand: "Bala Tours & Travels",
  tagline: "TAXI & TOURS • HIMACHAL PRADESH",
  heroKicker: "TAXI & TOURS • HIMACHAL PRADESH",
  heroTitle: "Your Journey Our Responsibility",
  heroText: "Comfortable, safe and reliable taxi services for local and outstation travel across Himachal Pradesh.",

  phone: ["+91-9882210063", "+91-7018110063"],
  whatsapp: "917018110063",
  email: "balatoursandtravels4272@gmail.com",
  address: "H.No. 214/12 ramnagar Mandi [H.P]",

  stats: [["50+", "Luxury Fleet"], ["13.8k+", "Guests Carried"], ["1000+", "5-Star Reviews"]],

  locations: [
    "Mandi","Ramnagar Mandi","IIT Mandi","Sundernagar","Kullu","Bhuntar","Manali","Kasol","Manikaran","Naggar",
    "Shimla","Kufri","Chail","Narkanda","Kasauli","Dharamshala","McLeod Ganj","Palampur","Bir Billing","Baijnath",
    "Dalhousie","Khajjiar","Chamba","Kangra","Una","Hamirpur","Bilaspur","Chintpurni","Jwala Ji","Naina Devi",
    "Kinnaur","Kalpa","Reckong Peo","Sangla","Chitkul","Spiti Valley","Kaza","Tabo","Kibber","Keylong","Sissu",
    "Rohtang Pass","Atal Tunnel","Chandigarh","Mohali","Panchkula","Ambala","Delhi","Amritsar","Pathankot",
    "Jalandhar","Ludhiana","Patiala","Dehradun","Haridwar","Rishikesh","Jammu",
    "Joginder Nagar","Dharampur","Sarkaghat","Baldwara","Rewalsar","Prashar Lake","Pandoh","Aut","Banjar",
    "Tirthan Valley","Jibhi","Shoja","Jalori Pass","Naggar Castle","Solang Valley","Old Manali","Vashisht",
    "Kullu Dussehra Ground","Manali Bus Stand","Mandi Bus Stand","Mandi Railway Station","Joginder Nagar Railway Station",
    "Bhuntar Airport","Chandigarh Airport","Kangra Airport","Shimla Airport","Pathankot Railway Station",
    "Chandigarh Railway Station","Kalka","Parwanoo","Pinjore","Baddi","Nalagarh","Nahan","Paonta Sahib",
    "Sirmaur","Renuka Ji","Sirmauri Tal","Solan","Barog","Arki","Theog","Rohru","Rampur Bushahr","Sarahan",
    "Sangla Valley","Nako","Dhankar","Pin Valley","Kunzum Pass","Lahaul Valley","Udaipur Himachal","Jispa",
    "Darcha","Keylong Bus Stand","Manali Mall Road","Shimla ISBT","Shimla Railway Station","Chandigarh ISBT",
    "ISBT Tutikandi","Dharamshala Bus Stand","McLeod Ganj Main Square","Palampur Bus Stand","Dalhousie Bus Stand",
    "Kullu Bus Stand","Mandi Market","Vijaypur Mandi","Ner Chowk","Medical College Ner Chowk","Nagwain",
    "Bajaura","Bhuntar","Raison","Patlikuhal","Katrain","Marhi","Koksar","Sissu Lake","Darcha Check Post"
  ],

  nav: [["Home","#home"],["About Us","#about"],["Services","#services"],["Fleets","#fleets"],["Contact Us","#contact"]],

  services: [
    ["Local Taxi Service","Reliable local taxi rides for Mandi and nearby areas."],
    ["Weekend Getaways","Comfortable trips to Manali, Shimla, Dharamshala, Spiti and more."],
    ["Outstation Taxi","One-way and round-trip taxi services across Himachal Pradesh and nearby states."],
    ["Airport Transfers","Convenient pickup and drop services for airport travel."],
    ["Railway Station","On-time railway station pickup and drop for a smooth journey."],
    ["Tour & Travel","Custom taxi and tour arrangements for families, groups and businesses."]
  ],

  fleets: [
    ["Hatchback","Ideal for solo travellers and city rides.","4-5","Ask for price"],
    ["Sedan","Comfortable choice for small families and groups.","4","Ask for price"],
    ["SUV","Perfect for hills and longer group trips.","6-7","Ask for price"],
    ["Tempo Traveller","Ideal for family tours and groups.","9-17","Ask for price"],
    ["Luxury Cars","Premium travel for special occasions.","4","Ask for price"],
    ["Mini Bus","Convenient transport for larger groups.","20+","Ask for price"],
    ["Outstation Taxi","Comfortable long-distance travel.","4-7","Ask for price"],
    ["One Way Drop","Point-to-point travel without a return trip.","4-7","Ask for price"]
  ],

  reasons: [
    ["Safe Travel","Experienced drivers and dependable service for every journey."],
    ["Affordable Pricing","Competitive and transparent pricing for local and outstation trips."],
    ["Professional Chauffeurs","Experienced drivers who understand Himachal roads."],
    ["24/7 Availability","Travel support for early morning and late-night journeys."],
    ["Local Expertise","Drivers familiar with Himachal routes and destinations."],
    ["Well-Maintained Fleet","Clean and comfortable vehicles for your journey."]
  ],

  destinations: [
    ["Mandi","Gateway to many beautiful destinations in Himachal Pradesh."],
    ["Ramnagar Mandi","Convenient local pickup point in Mandi."],
    ["IIT Mandi","Taxi pickup and drop for IIT Mandi."],
    ["Sundernagar","Local and outstation taxi service."],
    ["Kullu","Beautiful valley, rivers, temples and local culture."],
    ["Bhuntar","Convenient airport and Kullu valley transfers."],
    ["Manali","Snow peaks, adventure activities and beautiful valleys."],
    ["Kasol","Popular Himalayan destination in Parvati Valley."],
    ["Manikaran","Famous hot springs and pilgrimage destination."],
    ["Naggar","Historic village with mountain views."],
    ["Shimla","Explore the Queen of Hills and its famous Mall Road."],
    ["Kufri","Popular mountain getaway near Shimla."],
    ["Chail","Peaceful hill destination surrounded by forests."],
    ["Narkanda","Scenic apple-growing hill town."],
    ["Kasauli","A peaceful hill town surrounded by pine forests."],
    ["Dharamshala","Mountains, monasteries and peaceful surroundings."],
    ["McLeod Ganj","Tibetan culture, cafes and Himalayan views."],
    ["Palampur","Tea gardens and beautiful Dhauladhar views."],
    ["Bir Billing","Famous paragliding destination."],
    ["Baijnath","Historic temple town near Palampur."],
    ["Dalhousie","Pine forests, colonial charm and scenic mountain views."],
    ["Khajjiar","Beautiful meadow often called Mini Switzerland."],
    ["Chamba","Historic town with temples and mountain scenery."],
    ["Kangra","Historic valley and important Himachal destination."],
    ["Una","Important town and gateway to Himachal."],
    ["Hamirpur","Popular central Himachal town."],
    ["Bilaspur","Town near Gobind Sagar Lake."],
    ["Chintpurni","Important pilgrimage destination."],
    ["Jwala Ji","Famous temple town in Kangra."],
    ["Naina Devi","Popular hilltop pilgrimage destination."],
    ["Kinnaur","Scenic Himalayan district known for valleys and villages."],
    ["Kalpa","Beautiful Kinnaur destination with mountain views."],
    ["Reckong Peo","Gateway to Kinnaur."],
    ["Sangla","Scenic Baspa Valley destination."],
    ["Chitkul","Famous village near the India-Tibet border."],
    ["Spiti Valley","A spectacular cold desert mountain journey."],
    ["Kaza","Main town and travel base in Spiti."],
    ["Tabo","Ancient monastery village in Spiti."],
    ["Kibber","High-altitude village near Kaza."],
    ["Keylong","Gateway town to Lahaul."],
    ["Sissu","Beautiful Lahaul valley destination."],
    ["Rohtang Pass","Popular high mountain destination near Manali."],
    ["Atal Tunnel","Major travel attraction near Manali."],
    ["Chandigarh","Major pickup and drop city for Himachal travel."],
    ["Mohali","Airport and city transfers."],
    ["Panchkula","Pickup and drop for Himachal journeys."],
    ["Ambala","Convenient railway and road transfer point."],
    ["Delhi","Long-distance pickup and drop service."],
    ["Amritsar","Punjab pickup and Himachal tour connection."],
    ["Pathankot","Railway station and travel connection."],
    ["Jalandhar","Outstation pickup and drop."],
    ["Ludhiana","Outstation pickup and drop."],
    ["Patiala","Outstation pickup and drop."],
    ["Dehradun","Outstation pickup and drop."],
    ["Haridwar","Outstation pickup and pilgrimage trips."],
    ["Rishikesh","Outstation pickup and drop."],
    ["Jammu","Long-distance travel and Himachal connection."]
  ],

  temples: [
    ["Hidimba Devi Temple","Ancient temple surrounded by cedar forests in Manali."],
    ["Baijnath Temple","Historic Shiva temple near Palampur."],
    ["Jwala Ji Temple","Famous pilgrimage destination known for its eternal flame."],
    ["Naina Devi Temple","Hilltop temple with beautiful surrounding views."],
    ["Chintpurni Temple","One of Himachal's important Shakti pilgrimage sites."],
    ["Bijli Mahadev Temple","Famous Shiva temple near Kullu."],
    ["Baba Balak Nath Temple","Popular pilgrimage destination in Himachal Pradesh."],
    ["Bagalamukhi Temple","A well-known temple at Bankhandi."]
  ]
};